name: qisdax
channels:
  - defaults
dependencies:
  - git
  - pip
  - python<3.10
  - pip:
    - git+https://github.com/m-labs/artiq.git
    - git+https://gitlab.com/duke-artiq/dax@v6.8
    - git+https://gitlab.com/duke-artiq/dax-program-sim.git
    - qiskit==0.36.2
    - git+https://github.com/m-labs/sipyco@v1.4
