name: qisdax
channels:
  - https://conda.m-labs.hk/artiq
  - defaults
  - conda-forge
dependencies:
  - dax
  - git
  - pip
  - python
  - pip:
    - qiskit
    - llvmlite
    - git+https://gitlab.com/duke-artiq/dax-program-sim.git
